version: '3.8'

services:
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #   - .env
  #   command: yarn start:dev
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   depends_on:
  #     - postgres
  #   networks:
  #     - online-test

  postgres:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./db-data/postgresql:/var/lib/postgresql/data
      - ./db-data/docker-entrypoint:/docker-entrypoint-initdb.d
    networks:
      - online-test

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    networks:
      - online-test
networks:
  online-test:
